# permissions for end users to edit apiversions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: stilas-az
    app.kubernetes.io/managed-by: kustomize
  name: apiversion-editor-role
rules:
- apiGroups:
  - apim.azure.stilas.418.cloud
  resources:
  - apiversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apim.azure.stilas.418.cloud
  resources:
  - apiversions/status
  verbs:
  - get
