# permissions for end users to view productapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: stilas-az
    app.kubernetes.io/managed-by: kustomize
  name: productapi-viewer-role
rules:
- apiGroups:
  - apim.azure.stilas.418.cloud
  resources:
  - productapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apim.azure.stilas.418.cloud
  resources:
  - productapis/status
  verbs:
  - get
