---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apim.azure.stilas.418.cloud
  resources:
  - productapis
  - productapiversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apim.azure.stilas.418.cloud
  resources:
  - productapis/finalizers
  - productapiversions/finalizers
  verbs:
  - update
- apiGroups:
  - apim.azure.stilas.418.cloud
  resources:
  - productapis/status
  - productapiversions/status
  verbs:
  - get
  - patch
  - update
