//go:build !ignore_autogenerated

/*
Copyright 2024 tjololo.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIContactInformation) DeepCopyInto(out *APIContactInformation) {
	*out = *in
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIContactInformation.
func (in *APIContactInformation) DeepCopy() *APIContactInformation {
	if in == nil {
		return nil
	}
	out := new(APIContactInformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProductApi) DeepCopyInto(out *ProductApi) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProductApi.
func (in *ProductApi) DeepCopy() *ProductApi {
	if in == nil {
		return nil
	}
	out := new(ProductApi)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProductApi) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProductApiList) DeepCopyInto(out *ProductApiList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProductApi, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProductApiList.
func (in *ProductApiList) DeepCopy() *ProductApiList {
	if in == nil {
		return nil
	}
	out := new(ProductApiList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProductApiList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProductApiSpec) DeepCopyInto(out *ProductApiSpec) {
	*out = *in
	if in.Products != nil {
		in, out := &in.Products, &out.Products
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ApiVersionScheme != nil {
		in, out := &in.ApiVersionScheme, &out.ApiVersionScheme
		*out = new(APIVersionScheme)
		**out = **in
	}
	if in.ApiType != nil {
		in, out := &in.ApiType, &out.ApiType
		*out = new(APIType)
		**out = **in
	}
	if in.Contact != nil {
		in, out := &in.Contact, &out.Contact
		*out = new(APIContactInformation)
		(*in).DeepCopyInto(*out)
	}
	if in.ContentFormat != nil {
		in, out := &in.ContentFormat, &out.ContentFormat
		*out = new(ContentFormat)
		**out = **in
	}
	if in.Content != nil {
		in, out := &in.Content, &out.Content
		*out = new(string)
		**out = **in
	}
	if in.SubscriptionRequired != nil {
		in, out := &in.SubscriptionRequired, &out.SubscriptionRequired
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProductApiSpec.
func (in *ProductApiSpec) DeepCopy() *ProductApiSpec {
	if in == nil {
		return nil
	}
	out := new(ProductApiSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProductApiStatus) DeepCopyInto(out *ProductApiStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProductApiStatus.
func (in *ProductApiStatus) DeepCopy() *ProductApiStatus {
	if in == nil {
		return nil
	}
	out := new(ProductApiStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProductApiVersion) DeepCopyInto(out *ProductApiVersion) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProductApiVersion.
func (in *ProductApiVersion) DeepCopy() *ProductApiVersion {
	if in == nil {
		return nil
	}
	out := new(ProductApiVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProductApiVersion) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProductApiVersionList) DeepCopyInto(out *ProductApiVersionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProductApiVersion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProductApiVersionList.
func (in *ProductApiVersionList) DeepCopy() *ProductApiVersionList {
	if in == nil {
		return nil
	}
	out := new(ProductApiVersionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProductApiVersionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProductApiVersionSpec) DeepCopyInto(out *ProductApiVersionSpec) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProductApiVersionSpec.
func (in *ProductApiVersionSpec) DeepCopy() *ProductApiVersionSpec {
	if in == nil {
		return nil
	}
	out := new(ProductApiVersionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProductApiVersionStatus) DeepCopyInto(out *ProductApiVersionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProductApiVersionStatus.
func (in *ProductApiVersionStatus) DeepCopy() *ProductApiVersionStatus {
	if in == nil {
		return nil
	}
	out := new(ProductApiVersionStatus)
	in.DeepCopyInto(out)
	return out
}
